<?php

    /*
    
        localhost Ltd - ALPHA Framework
        
        Version: 10.0
        
        File name: root.phtml
        Description: This file contains the root view.
        
        Coded by George Delaportas (G0D)
        
        localhost Ltd
        Copyright (c) 2012
    
    */

?>



    <div id="main_content">
        
    </div>



<?php /* ---------- End ---------- */ ?>
